#!/bin/bash
#

# If on Mac, assumed that sed has been aliased to use 'gsed -r'
machine=$(uname)
if [ $machine == 'Darwin' ]
then
    sed_cmd='gsed -r'
else
    sed_cmd='sed'
fi

# Remove trailing whitespace from all files that are being committed.
files=$(git status --porcelain | grep "^[A-Z]\s" | awk -F" " '{print $2}')
for f in $files
do
    $sed_cmd -i 's/\s*$//' $f
    git add $f
done
