#!/bin/bash
#

# If on Mac, assume that gnu-sed has been installed with brew
machine=$(uname)
if [ $machine == 'Darwin' ]
then
    if [ $(which gsed) ]
    then
        sed_cmd='gsed -r'
    else
        echo 'WARNING: Install gnu-sed to use pre-commit hook: `brew install gnu-sed`'
        exit
    fi
else
    sed_cmd='sed'
fi

# Remove trailing whitespace from all files that are being committed.
files=$(git status --porcelain | grep "^[A-Z]\s" | awk -F" " '{print $2}')
for f in $files
do
    $sed_cmd -i 's/\s*$//' $f
    git add $f
done
